<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <OutputType>library</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http"/>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid"/>
        <PackageReference Include="OpenTelemetry"/>
        <PackageReference Include="OpenTelemetry.Exporter.Console"/>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"/>
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore"/>
        <PackageReference Include="Swashbuckle.AspNetCore"/>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Jobee.Workplace.Shared.Infrastructure\Jobee.Workplace.Shared.Infrastructure.csproj" />
    </ItemGroup>
</Project>
